name = "glimra"
version = "2.0.2"
gleam = ">= 1.4.0"
target = "erlang"
description = "Zero runtime syntax highlighter for lustre/ssg."
licences = ["MIT"]
repository = { type = "github", user = "ollema", repo = "glimra" }

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
lustre = ">= 5.3.1 and < 6.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
lustre_ssg = ">= 0.11.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.3 and < 2.0.0"
