name: test

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  compile-nifs:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x86_64
          - os: macos-latest
            target: macos-aarch64
          - os: macos-13
            target: macos-x86_64
          - os: windows-latest
            target: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: setup rust cache
        uses: swatinem/rust-cache@v2.7.3
      - name: build NIF
        run: cargo xtask
      - name: upload NIF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: priv/lib/*

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x86_64
          - os: windows-latest
            target: windows-x86_64
    runs-on: ${{ matrix.os }}
    needs: compile-nifs
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup gleam
        uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - name: test formatting
        run: gleam format --check src test
        if: ${{ matrix.os != 'windows-latest' }}
      - name: download dependencies
        run: gleam deps download
      - name: download NIF
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: priv/lib
      - name: test
        run: gleam test --target erlang
        # TODO: enable when/if birdie works on windows 
        if: ${{ matrix.os != 'windows-latest' }} 

